version: '3'

services:
  playlist-converter:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: uvicorn webpage.backend.api:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src
    environment:
      - PYTHONPATH=/app/src 